import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import TextEditor from '@/TextEditor/TextEditor'
import React from 'react';
import Link from 'next/link';
import Entrance from '../src/Components/Entrance/Entrance';

export default function Home() {
  return (
    <>
      <Head>
        <title>Elysium notes day</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

      </Head>
      
      <Entrance/>
    </>
  )
}
